
#include <stdio.h>

int main()
{
   int senha=0;
   printf("digite uma senha \n");
   scanf("%d",&senha);
    
 for(int i = 0; i < 10; i++){
       for(int x= 0; x <10; x++){
           for(int y = 0; y< 10; y++){
               for(int z = 0; z < 10; z++){
                  printf("valor:%d %d %d %d \n" ,i,x,y,z);
               }
           }
           
          
           
      
       }
   }
   
}
